languageCode = "en"
languageName = "English"
weight = 1
title = "Diego R.N."

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[author]
  name = "Diego"
  image = "img/avatar.webp"
  headline = "Violinista Huapanguero"
  bio = "Un Violinista Huapanguero"
  # links = [
  #   { link = "https://nunocoracao.github.io/blowfish/" },
  #   { github = "https://github.com/nunocoracao/blowfish" },
  #   { x-twitter = "https://twitter.com/burufugu" }
  # ]
